stages:
  - test

test_job:
  stage: test
  script:
    - echo "Sleeping for 120 seconds..."
    - sleep 120
    - |
      if [ -f .ci-attempt ]; then
        echo "Second attempt - succeeding!"
        exit 0
      else
        echo "First attempt - failing on purpose."
        touch .ci-attempt
        exit 1
      fi
  cache:
    key: test-job-cache
    paths:
      - .ci-attempt
  retry:
    max: 1
    when:
      - script_failure
