name: 'Ensure CI Success'
description: 'Ensure all CI checks and commit statuses pass on a PR'
author: 'Charles de Beauchesne'
inputs:
  github-token:
    description: 'GitHub token to access PR commit statuses and checks'
    required: true
  initial-wait-seconds:
    description: 'Number of seconds to sleep before checking CI statuses'
    required: false
    default: '10'
  retries:
    description: 'Number of retries to wait for checks still in progress'
    required: false
    default: '5'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'