name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: read
  statuses: read
  contents: read
  packages: read

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  parent:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  child-success:
    runs-on: ubuntu-latest
    needs:
      - parent
    steps:
      - run: exit 0

  child-fail:
    runs-on: ubuntu-latest
    needs:
      - parent
    steps:
      - run: exit 1

  allcheckspassed:
    runs-on: ubuntu-latest
    needs:
      - success
      - fail
      - child-success
      - child-fail
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          checks_exclude: 'build-and-test'

  build-and-test:
    runs-on: ubuntu-latest
    needs:
      - success
      - fail
      - child-success
      - child-fail

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run format:check

      - name: Lint the code
        run: npm run lint

      - name: Build action
        run: npm run build

      - name: Validate that dist/ is up-to-date
        run: |
          git diff --exit-code dist/ || (echo "::error::dist/ is outdated, please run npm run build and commit the changes." && exit 1)

      - name: Test the action on itself
        uses: ./
        with:
          ignored-name-patterns: |
            allcheckspassed
