name: tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: read
  statuses: read
  contents: read
  packages: read

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  parent:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  child-success:
    runs-on: ubuntu-latest
    needs: 
      - parent
    steps:
      - run: exit 0

  child-fail:
    runs-on: ubuntu-latest
    needs: 
      - parent
    steps:
      - run: exit 1
