name: tmp

on:
  push:

concurrency:
  group: tmp-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: read
  statuses: read
  contents: read

jobs:
  build-and-test:
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Test the action on itself
        uses: ./
